### ISSUE TITLE
jumping div - contribute page (mobile)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1087]
If you switch between Speak and Listen on mobile then the sentence div jumps (different absolute top value), which makes the whole layout jump a bit.

**Comment by Gregoor** [comment]
looks good to me now :)

**Comment by Djfe** [comment]
1/5 Aufzeichnungen still jumps to the right
skip on listening is further left than submit on listening

the rest is fixed :)

pls reopen

**Comment by Djfe** [comment]
ups, I just noticed that this issue was about mobile only
The ones I just reported are on desktop.

On mobile (listening page) there is one thing left (only present in the german translation)
![screenshot_20181214-105144](https://user-images.githubusercontent.com/5685512/49996123-6af9e100-ff8e-11e8-960d-0a5bbb12b6d1.png)
https://pontoon.mozilla.org/de/common-voice/all-resources/?search=gut+so&string=179060
Do I have to find a way to shorten the string or are you able to adjust the layout, so that two-line sentences don't affect the top distance of the buttons below

**Comment by mbransn** [comment]
This issue is still relevant, adding back help wanted as this isn't something the staff team will be able to tackle immediately. Ideally we create front-end vertical spacing consistency as best possible with localization needs -- this may be part of accessibility work as well.

**Comment by ftyers** [comment]
I just tested this on mobile and it is no longer an issue.

**Comment by Djfe** [comment]
yeah, this was just a relic from back then ^^
