### ISSUE TITLE
Menu options are displayed twice on the page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1631]
[Environment]:
Windows 10, Ubuntu 16.04 - Firefox, Chrome

[Steps to reproduce]:
1.Open https://voice.allizom.org/en
2.Reduce window dimensions until the navigation bar options are not displayed
3.Click the menu (three dots or profile picture) located in the upper right corner
4.Maximize the window

[Actual result]:
The options are displayed in the navigation bar and also above in the page
![2018-11-28_18h54_57](https://user-images.githubusercontent.com/41474886/49167924-1aa04380-f33f-11e8-859a-c912d6594401.png)

**Comment by snpd25** [comment]
@rleitan , Can't reproduce this issue, maybe it is fixed now.

**Comment by MichaelKohler** [comment]
I can still reproduce this.

<img width="1190" alt="Screenshot 2020-03-09 at 09 59 16" src="https://user-images.githubusercontent.com/330324/76197562-479b0180-61e4-11ea-8e70-4cf63cd29a86.png">

**Comment by aryamanpuri** [comment]
I just want to confirm one thing about this issue that whether to preserve the calling of the above `navigation modal` after minimizing the window after the STR 4 or the navigation modal shouldn't be rendered. As the user can resize the screen as their need and the last behavior should be preserved. 
Btw I can reproduce this issue too.

**Comment by phirework** [comment]
If the mobile navigation was *open* at a small screen size, it should: 
* close when the user resizes the screen to be a full desktop size
* re-open if the user resizes the screen to be a small size again

**Comment by rileyjshaw** [comment]
Will be fixed on master on next deploy

**Comment by rileyjshaw** [comment]
Will be fixed on master on next deploy
