### ISSUE TITLE
'Speak' page blurry after hovering the 'Submit' button

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#195]
[Affected versions]:
- Chrome 59

[Affected platforms]:
- Win 10

[Steps to reproduce]:
1. Open https://voice.allizom.org/
2. Go to the "Speak" page
3. Complete 3 recordings
4. Hover the 'Submit' button with mouse

[Expected result]:
- 'Speak' page displayed properly

[Actual result]:
- Blurry text - screencast: https://www.screencast.com/t/qjq4CRtl

**Comment by mikehenrty** [comment]
@paulsilaghi thanks for the report here. can you use another image service than screencast? it requires flash for some reason, and i'd rather avoid installing that if i can :)

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Is this text just moving or it it blurry? From the video it looks more like it's just moving a bit.

**Comment by paulsilaghi** [comment]
I think you're right, it's just moving a bit. Thanks, Kelly.

**Comment by paulsilaghi** [comment]
https://www.youtube.com/watch?v=SFNO8VQnF6k

**Comment by mikehenrty** [comment]
let's change the hover styling to color rather than zoom

**Comment by mikehenrty** [comment]
fixed in: https://github.com/mozilla/voice-web/commit/20ce1af94ec14b75af5674cbc0a0454ca9c1c268

**Comment by paulsilaghi** [comment]
I still see a text moving right after the 'Submit' page is displayed, but unrelated to the hovering of the 'Submit' button - https://www.youtube.com/watch?v=G7jlX0mCJns

**Comment by mikehenrty** [comment]
I think this is browser quirk, and not much we can do from the app side.
