### ISSUE TITLE
User receives "50+ points" banner after every validation

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2319]
STR:

1. Sign up to the challenge for a team 
2. Navigate to challenge page and change the date (use [this](https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20) url)
3. Click "Listen" button in the Current Challenge section
4. Validate first sentence => User gets "50 + points" banner
5. Validate second sentence

**Expected:**
User is redirected to next sentence, the banner is not displayed anymore

**Actual:**
User gets the "50+ points" banner displayed again

![challenge validation-2019-11-14_12 22 58](https://user-images.githubusercontent.com/5293100/68849419-b656cb00-06da-11ea-9087-be9cb55fac67.gif)

**Comment by catherine917** [comment]
For the front-end, I removed the achievements related items from the sessionStorage. And @Can also suggested modifying the launch date in the database. So it should be fixed now and need to confirm again.

**Comment by viorelaioia** [comment]
This is partially fixed. Now the notification is displayed for the first 2 validations made.

**Comment by phirework** [comment]
@catherine917's changes hadn't been merged in yet so if there was a partial fix it wasn't from us. I've merged it in now, it should be on staging in ~30 min.

**Comment by viorelaioia** [comment]
Verified as fixed!
