### ISSUE TITLE
Unify Dialogs

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#234]
font is different, button side is different, hover state is different

**Comment by mikehenrty** [comment]
Can we make them look more similar to each other?

**Comment by elahmo** [comment]
Are these still active? The Tems page seems aligned with other ones, and I couldn't find the dialogue for deletion of recordings at all, so I am wondering is this solved in some other contribution.

**Comment by mikehenrty** [comment]
Hi @elahmo. This is indeed still a problem, as we have 2 ways to show a confirm dialog.

When a user is agreeing to our Terms of Service, we embed the pop-up in the Pages component:
https://github.com/mozilla/voice-web/blob/bb08e7973a0434c4e13374558c1421ad5094dc12/web/src/lib/components/pages.tsx#L481

But when a user is asked whether or not to keep their recordings, we use the confirm component:
https://github.com/mozilla/voice-web/blob/bb08e7973a0434c4e13374558c1421ad5094dc12/web/src/lib/components/pages/record.tsx#L259

We would like it if the Terms of Service dialog uses the confirm dialog if possible:
https://github.com/mozilla/voice-web/blob/bb08e7973a0434c4e13374558c1421ad5094dc12/web/src/lib/components/confirm.ts#L9
