### ISSUE TITLE
Other languages can break the dashboard

### ISSUE THREAD

**Issue by Mte90** [mozilla/voice-web#2434]
![immagine](https://user-images.githubusercontent.com/403283/69718742-654dca80-110f-11ea-9b5b-744bfb246822.png)

This is the case of Italian that break the dashboard.

**Comment by MichaelKohler** [comment]
Same goes for German, FWIW.

**Comment by Mte90** [comment]
I see this in the about page in the bottom, seems that the text is not aligned
![immagine](https://user-images.githubusercontent.com/403283/69957773-aaa13c00-1503-11ea-8e3e-bdbd741736c1.png)

**Comment by mbransn** [comment]
@Mte90 @MichaelKohler are there recommendations you all can give in these languages to our localization team to improve the translation, especially in cases of button text? cc @peiying2

**Comment by Mte90** [comment]
I don't think that is something possible, because Italian and German as example are languages with long words compared to english.
I remember other Mozilla portal with those issues and sometimes is something possible with CSS (like my second screen) other times is something that require UI changes.

**Comment by mbransn** [comment]
Thanks @Mte90 it's a great point, something @phirework also brought up yesterday. We've got it logged and will work to get it into the maintenance work we're planning for the next couple months.

**Comment by rileyjshaw** [comment]
This should be fixed by https://github.com/mozilla/voice-web/pull/2510.

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/71719466-bc397480-2e1e-11ea-98e4-40734aa8916d.png)
I can still see the issues but I don't know if the deploy was already done of those changes.

**Comment by rileyjshaw** [comment]
Thanks for following up @Mte90, and sorry for not communicating status better. The change is currently on https://voice.allizom.org/en, and will be deployed to the live site soon 😄

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/1840854/71756750-3d583200-2e46-11ea-8df7-c8287ece7df1.png">

**Comment by mbransn** [comment]
@rileyjshaw is this something we're tracking as ready for QA by @ovidiuboca1 @viorelaioia?

**Comment by rileyjshaw** [comment]
@mbransn it's not tracked in Jira as far as I can tell; @phirework made the initial commit, I'm just helping with issue wrangling. I can add something to Jira, unless @phirework already did so?

This raises a larger question about QA handoffs for Github issues. Do we want to duplicate all issues from here to Jira, or is a ping / assignment over Github (as above) sufficient?

I'm easy either way, maybe we can bring this into our workshop next week.

**Comment by phirework** [comment]
@mbransn Nope this wasn't tracked separately, the reports came directly from the community and I threw it in with a bunch of other fixes I was doing as part of my Github ticket (https://jira.mozilla.com/browse/OI-1348). My sense is that duplicating tickets for things that have already been fixed seems overkill, but happy to discuss in person this week.

**Comment by mbransn** [comment]
Cool, and nope, not saying we should bring into Jira. Highlighting that we need to ping QA on this prior to closing for verify and if we start to see an uptick in work that needs QA time, a flag is helpful in Slack standup at minimum so I can help wrangle. Blind otherwise and want to make sure we alleviate redundancies for everyone. Pulling into our doc and yes, hopefully we can talk through in person. Thanks!
