### ISSUE TITLE
Add record icon to mobile speak instructions callout

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2485]
Via @Fjoerfoks on slack:

> I noticed a difference between the desktop website and the mobile website when going to the speak part https://voice.mozilla.org/en/speak. On the desktop website the instruction reads "Click {record-icon} then read the sentence aloud", on the mobile site I see "Tap then read the sentence aloud", while it seems from Pontoon https://pontoon.mozilla.org/nl/common-voice/all-resources/?string=179048 there should be a record icon after "Tap.." too, otherwise the localized string doesn't make sense.

**Comment by Fjoerfoks** [comment]
BTW, this is also applicable for the Listen part of the mobile version, the icon misses there too.

**Comment by ayushbansal07** [comment]
It happens because the css ".contribution .instruction svg" has 'display' attribute set to 'none'. Only when the @media (min-width: 768px) conditions becomes true, the 'display' is set to initial. One quick fix for this would be to set style="display: initial" to the svg tag in that element.

**Comment by rileyjshaw** [comment]
This was fixed in https://github.com/mozilla/voice-web/pull/2510. This should be visible _now_ on voice.allizom.org, and _soon_ on voice.mozilla.org :)

**Comment by Fjoerfoks** [comment]
Thanks for working on this. But as far as I can see it is not fixed on production (yet) and on staging the Speak and Listen section are completely blank, so something went wrong somehow.
Can you take a look again?
