### ISSUE TITLE
Update avarage length of a sentence for better statisctics on /languages

### ISSUE THREAD

**Issue by stefangrotz** [mozilla/voice-web#2814]
Since the last release of the dataset the numbers of hours in the statistics on /datasets is higher than the hours on /languages for many languages. We discussed this on matrix and it turned out that this happens because the average sentence length has changed over time and it wasn't updated on the website. 

For example German has 686 validated hours in the 2020-06-22 dataset but only 672h on /languages (13th of July).

**Comment by phirework** [comment]
Thanks for reporting! This was fixed in the [sprint 31 release](https://github.com/mozilla/voice-web/releases/tag/release-v1.31.0) (you may not see the numbers update until tomorrow because those values are cached.)

**Comment by stefangrotz** [comment]
Thanks, its working now on /languages , but the data on the start page is still not updated
